<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Include the colors and inertial_macros xacro files -->
    <xacro:include filename="colors.xacro" />
    <xacro:include filename="inertial_macros.xacro" />

    <!-- Chassis properties -->
    <xacro:property name="base_width" value="0.17"/>
    <xacro:property name="base_length" value="0.25"/>
    <xacro:property name="base_height" value="0.06"/>

    <!-- Wheel properties -->
    <xacro:property name="wheel_radius" value="0.0215"/>
    <xacro:property name="wheel_width" value="0.012"/>
    <xacro:property name="wheel_ygap" value="-0.018"/>
    <xacro:property name="wheel_zoff" value="0.03"/>
    <xacro:property name="wheel_xoff" value="0.09"/>


    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${(wheel_radius+wheel_zoff)}" rpy="0 0 0" />
    </joint>

    <!-- Chassis -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="orange" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="1.3" y="${base_width}" x="${base_length}" z="${base_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="base_link">
            <material>Gazebo/Orange</material>
    </gazebo>

    <!-- Wheel Template -->
    <xacro:macro name="front_wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/> 
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <!-- <surface>
                    <friction>
                        <ode>
                            <mu>2.0</mu>
                            <mu2>2.0</mu2>
                            <fdir1>0 0 1</fdir1>
                        </ode>
                    </friction>
                </surface> -->
            </collision>

            <xacro:inertial_cylinder mass="0.1" radius="${wheel_radius}" length="${wheel_width}">
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="${prefix}_steering_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="0 1 0" rpy="0 0 0"/>
            <limit effort="100" velocity="10"/>
            <dynamics damping="0.1" friction="0.2"/>
        </joint>

        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="rear_wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/> 
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>

            <xacro:inertial_cylinder mass="0.1" radius="${wheel_radius}" length="${wheel_width}">
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
            <axis xyz="0 1 0" rpy="0 0 0"/>
            <limit effort="100" velocity="10"/>
            <dynamics damping="0.1" friction="0.2"/>
        </joint>

        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <!-- Steering Template -->
    <xacro:macro name="steering" params="prefix x_reflect y_reflect">
        <link name="${prefix}_steering_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                <cylinder radius="0.006" length="0.03"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.006" length="0.03"/>
                </geometry>
                <material name="black"/>
            </visual>

            <xacro:inertial_cylinder mass="0.04" length="0.03" radius="0.006">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_steering_link"/>
            <origin xyz="${x_reflect*base_length/2 -0.05} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit lower="-0.6" upper="0.6" velocity="1.0" effort="25"/>
        </joint>
    </xacro:macro>

    <!-- Wheels -->
    <xacro:rear_wheel prefix="left_rear" x_reflect="-1" y_reflect="1" />
    <xacro:rear_wheel prefix="right_rear" x_reflect="-1" y_reflect="-1" />
    <xacro:front_wheel prefix="left_front" x_reflect="1" y_reflect="1" />
    <xacro:front_wheel prefix="right_front" x_reflect="1" y_reflect="-1" />

    <!-- Steering -->
    <xacro:steering prefix="left_front" x_reflect="1" y_reflect="1" />
    <xacro:steering prefix="right_front" x_reflect="1" y_reflect="-1" />

</robot>