controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    ack_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    bicycle_steering_controller:
      type: bicycle_steering_controller/BicycleSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ack_cont:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    rear_wheels_names: [base_left_wheel_rear_joint, base_right_wheel_rear_joint]
    front_wheels_names: [front_left_wheel_steering_joint, front_right_wheel_steering_joint]

    front_wheel_track: 1.04
    rear_wheel_track: 1.04
    wheelbase: 1.4
    front_wheels_radius: 0.2
    rear_wheels_radius: 0.2

bicycle_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    rear_wheels_names: [virtual_rear_wheel_joint]
    front_wheels_names: [virtual_steer_joint]

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    # front_wheel_track: 1.04
    # rear_wheel_track: 1.04
    wheelbase: 1.4
    front_wheel_radius: 0.2
    rear_wheel_radius: 0.2